version: "3.4"

x-common-variables: &common-variables
  MYSQL_DATABASE: imgLabel
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD
  REACT_APP_SERVER_PORT: 3001

services:
  mysql_db:
    image: mysql
    container_name: mysql_container
    ports:
      - 3306:3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server:
    build: ./server
    container_name: node_server_container
    depends_on:
      - mysql_db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
    ports:
      - 3001:3001
    volumes:
      - ./server/:/app/
      -  /app/node_modules
    links:
      - mysql_db
    command: npm start
  client:
    build: ./client
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start
